import type { Metadata } from "next";
import { Inter } from "next/font/google";
import BusinessAppBar from "./components/BusinessAppBar";
import { ThemeProvider } from "@mui/material/styles";
import theme from "./theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "HomeShine RoofPro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{ margin: 0, display: "flex", flexDirection: "column" }}
      >
        <ThemeProvider theme={theme}>
          <BusinessAppBar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
